spring:
  application:
    name: csms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.cp.csms.common
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topics:
    auth-request: auth-request
    auth-response: auth-response
  consumer:
    transaction-service:
      group-id: transaction-service
    authentication-service:
      group-id: authentication-service

transaction-service:
  authorization:
    timeout-seconds: 5

logging:
  level:
    com.cp.csms: DEBUG
    org.springframework.web: DEBUG
    org.springframework.kafka: INFO

